CarRent/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarRent.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CarRent/Controllers/searchCarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CarRent.BL;
using CarRent.Models;

namespace CarRent.Controllers
{
    public class searchCarsController : Controller
    {
        // GET: searchCars
       
        public ActionResult Index()
        {
            using (CarManeger logic = new CarManeger())
            {
                List<Car> carList = logic.GetAllCars().ToList();
                return PartialView(carList);   
            }
        }
        public ActionResult Search()
        {    
                return View();
        }
       
        //[HttpPost]
        public ActionResult SearchResualt(int carYear, bool carGear, DateTime startRent, DateTime endRent) 
        {
            using (CarManeger logic = new CarManeger())
            {
                List<Car> carList = logic.SearchCars(carYear, carGear, startRent, endRent).ToList();
                return PartialView(carList);    
            }
        }
      
        }
       
    }

CarRent/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CarRent/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CarRent/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>אייל ונתי השכרת רכב בע"מ</h1>
    <p class="lead">שירות 24 שעות ביממה</p>
    <p class="lead"> !!!  אצל אייל ונתי השכרת רכב תוכל לשכור רכב לכל מטרה  </p>
    <img src="~/pictures/homepage.jpg" />
    @Html.ActionLink("Search", "Index", "searchCars")
    @*<div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li>@Html.ActionLink("Car Typs", "Index", "CarTypes")</li>

    </div>*@
</div>

<div class="row">
    @*<div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>*@
</div>